### ISSUE TITLE
collection of auditory perception models

### ISSUE THREAD

**Issue by PeerHerholz** [sensein/science4all#2]
Ahoi hoi folks,

a while back, @jsmentch and I thought about a little project to collect auditory perception models and bring them together in a small python package, comparable to e.g. [THINGSvision](https://www.frontiersin.org/articles/10.3389/fninf.2021.679838/full).

The idea would be:

- collect a broad range of `auditory perception models` (basic & DNN)
- harmonize their `setup` and `application`
- provide a small `python package` that allows `model` application to new `stimuli`, including `extraction` of respective `layer representations`

This could be utilized for various purposes, e.g.: `encoding models`, `brain` & `DNN` comparison, `semantic maps` & `manifolds` in general, etc. .

WDYT? I'm very sorry if this is out of scope for this repo.

Cheers, Peer

**Comment by jsmentch** [comment]
Yes! A great first step if anyone is interested in helping would be to gather a list of candidate models from around the web. Here is an example of one: https://pycochleagram.readthedocs.io/en/latest/readmeLink.html

**Comment by PeerHerholz** [comment]
Cool, thx @jsmentch!

Here are some other candidate models:

### ANN
- [soundnet](http://soundnet.csail.mit.edu/)
- [wav2vec2](https://arxiv.org/abs/2006.11477)
- [S2T](https://aclanthology.org/2020.aacl-demo.6.pdf)
- [SepFormer](https://paperswithcode.com/method/sepformer)
- [deepspeech2](https://github.com/sooftware/deepspeech2)
- [VQ-VAE](https://paperswithcode.com/method/vq-vae)
- [DCASE2020](https://dcase.community/challenge2020/index)
- [MetricGan](https://paperswithcode.com/paper/metricgan-an-improved-version-of-metricgan)
- [AST](https://arxiv.org/abs/2104.01778)
- [VGGish](https://github.com/tensorflow/models/tree/master/research/audioset/vggish)
- [yamnet](https://github.com/tensorflow/models/tree/master/research/audioset/yamnet)
- [kelletall2018](https://github.com/mcdermottLab/kelletal2018)
- [model metamers](https://github.com/mcdermottLab/model_metamers)
 
### "base" models
- good set of potential models included in [pliers](http://psychoinformaticslab.github.io/pliers/transformers.html#list-of-extractor-classes)

**Comment by aditmag** [comment]
Hi!

I'm interested in continuing R&D on this.
Would it be possible for me to intern at the lab this fall for the same?

Regards

**Comment by PeerHerholz** [comment]
key reference: https://www.biorxiv.org/content/10.1101/2022.09.06.506680v2.full.pdf

**Comment by aditmag** [comment]
> key reference: https://www.biorxiv.org/content/10.1101/2022.09.06.506680v2.full.pdf

Thank you! I'll have a look

**Comment by aditmag** [comment]
Had a look at the models :)
Let's get working!

@PeerHerholz @jsmentch  where exactly should I start? 

Regards

**Comment by aditmag** [comment]
Hi, I'm still interested in contributing to this!

Is the project still on?

**Comment by jsmentch** [comment]
At the moment I'm a bit swamped but can hopefully help with this in the new year

**Comment by PeerHerholz** [comment]
Sorry y'all, same here!

**Comment by satra** [comment]
I'm going to close this issue and restart when people have more time.
