### ISSUE TITLE
Highschool Intern!

### ISSUE THREAD

**Issue by dinapaul** [sensein/science4all#4]
Hi!
I hope this finds you well. I am reaching out because I came across your research on mental illness and neurological disorders, and found it to be extremely fascinating. For some background, I am a rising senior at Burlington High School and intend to major in neuroscience in college. For the past few months, I have interned at Northeastern’s Center for Cognitive and Brain Health as a research assistant, working alongside graduate students and postdocs to study how exercise affects cognition and brain health. This included experience with EEG, biospecimen collecting, MRIs, and more. Throughout this journey, I found a heavy interest in brain imaging and neurological disorders. Patients with mental illness and brain health issues were screened out of our research process, which often left me questioning- how would their brains scan under the MRI? How drastically would their EEG results differ? As I move on from my position at Northeastern, I would like to now focus on exploring the medicinal side of neuroscience. Discovering treatments and finding solutions to these brain health concerns is something I am passionate about, and hope to possibly study in the future. The Senseable Intelligence Group targets all of my research interests, therefore, I would be incredibly grateful for an opportunity to intern there.  Thank you for your time and consideration. Have a great day!

Respectfully yours,
Dina Paul
857-756-3280
dinapaul424@gmail.com

**Comment by satra** [comment]
@dinapaul - i'm really sorry no one followed up here. I will close this for now, but if you are still interested please reopen.
