### ISSUE TITLE
High School Intern :)

### ISSUE THREAD

**Issue by AlphaLaser** [sensein/science4all#5]
Hello! How are you doing?

I'm Adit, a high school Junior at Sanskriti School in New Delhi, India. My research interest lies in Medical Imaging and NLP for Speech Analysis. I am really passionate about research that makes a real-world impact. 

I have previously worked as a Medical Imaging Researcher at ARQuest Research Network where I worked on processing Retinal OCT Scans and classifying them using Convolutional Neural Networks on the basis of the condition of their cross-sections. Working on classifying Retinal tears had me wondering how efficient the medical system would become once AI became reliable enough. Millions of images would be processed in seconds. Healthcare would flourish.

I went through some of Sensein group's research papers and found them very informative! I especially liked the presentation on the Genetic Analysis of Schizophrenia. I had a look at some other projects as well and the group's research definitely aligns with my interests!

I would really love to work at the Sensein group as an unpaid remote research intern this fall. I would be immensely grateful for the opportunity.

Curriculum Vitae - [CV](https://drive.google.com/file/d/1epqGPjGS0wgK9TgrH0mNs5kR_X7Zao64/view?usp=sharing)
Reference - [Matthew Strong](https://github.com/peasant98) (Microsoft SWE, Ex Robotics-Researcher @ CU Boulder)

Thank you so much for your time

Warm Regards
Adit Magotra, (+91 9958877036)
[Email](mailto:aditmagotra@gmail.com) | [Linkedin](https://linkedin.com/in/AditMagotra) | [Github](https://github.com/AlphaLaser)

**Comment by satra** [comment]
I am going to close this issue. Please do reopen if you are still interested in pursuing projects.
